version: "3.9"
services:
  db:
    image: postgres:14-alpine
    restart: always
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: konikp1
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: kewrmaco123
    ports:
      - "7070:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgresql:
  pgadmin:
